# Generated by Django 5.0.1 on 2024-03-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccines',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
