# Generated by Django 5.0.1 on 2024-03-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0002_vaccines_available_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccines',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
