# Generated by Django 5.0.1 on 2024-03-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0003_vaccines_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccines',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vaccines/images/'),
        ),
    ]
