# Generated by Django 5.0.1 on 2024-03-09 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0003_alter_useraccount_userrole'),
        ('vaccines', '0004_alter_vaccines_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_dose_date', models.DateField(blank=True, null=True)),
                ('second_dose_date', models.DateField(blank=True, null=True)),
                ('Vaccines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccines.vaccines')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglogin.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comment', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vaccines.vaccines')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
