# Generated by Django 5.0.1 on 2024-03-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0005_borrow_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='vaccines',
        ),
    ]
