# Generated by Django 5.0.1 on 2024-03-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='nid_no',
            field=models.IntegerField(unique=True),
        ),
    ]
