# Generated by Django 5.0.1 on 2024-03-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0002_alter_useraccount_nid_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='userRole',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=10),
        ),
    ]
